blank_issues_enabled: true
contact_links:
  - name: Docs
    url: https://larzos.com/larz/docs/
    about: The Larz documentation
  - name: Free course
    url: https://larzos.com/academy/larz/
    about: Learn Larz from scratch
